import sys
import urllib.request
import os
import time

author="Grasiand"
print("AUTHOR Ꮆ尺卂丂İ卂几ᗪ")
print("Örnek : https://www.ornek.com ")

url = input("\nWebsite : ")

link = ('WSO.php/',
'alfav4.1-tesla.php/',
'k2.php/','who1.php/',
'config.php/','dz.php/',
'mailer.php/',
'promailer.php/',
'hexor.php/',
'fuck.php/',
'xz.php/',
'CaZaNoVa163.php/',
'w.php/',
'shell.php/',
'cpanel.php/',
'cpn.php/',
'sql.php/',
'mysql.php/',
'config.php/',
'configuration.php/',
'madspot.php/',
'Cgishell.pl/',
'killer.php/',
'changeall.php/',
'2.php/',
'Sh3ll.php/',
'dz0.php/',
'dam.php/',
'user.php/',
'dom.php/',
'whmcs.php/',
'r00t.php/',
'1.php/',
'va.php/',
'vr0k.php/',
'vabc.php/',
'egy.php/',
'syrian_shell.php/',
'xxx.php/',
'settings.php/',
'tmp.php/',
'cyber.php/',
'c99.php/',
'r57.php/',
'404.php/',
'gaza.php/',
'1.php/',
'd4rk.php/',
'index1.php/',
'nkr.php/',
'xd.php/',
'M4r0c.php/',
'vDz.php/',
'sniper.php/',
'ksa.php/',
'v4team.php/',
'offline.php/',
'priv8.php/',
'911.php/',
'madspotshell.php/',
'c100.php/',
'sym.php/',
'cp.php/',
'tmp/cpn.php/',
'tmp/w.php/',
'tmp/r57.php/',
'tmp/king.php/',
'tmp/sok.php/',
'tmp/ss.php/',
'tmp/as.php/',
'tmp/dz.php/',
'tmp/r1z.php/',
'tmp/whmcs.php/',
'tmp/root.php/',
'tmp/r00t.php/',
'templates/beez/index.php/',
'templates/beez/beez.php/',
'templates/rhuk_milkyway/index.php/',
'tmp/uploads.php/',
'tmp/upload.php/',
'tmp/sa.php/',
'sa.php/',
'readme.php/',
'tmp/readme.php/',
'wp-content/plugins/disqus-comment-system/disqus.php/',
'd0mains.phpwp-content/plugins/akismet/akismet.php/',
'madspotshell.php/',
'info.php/',
'egyshell.php/',
'Sym.phpc22.php/',
'c100.php/',
'wp-content/plugins/akismet/admin.php#/',
'configuration.php/',
'g.php/',
'wp-content/plugins/google-sitemap-generator/sitemap-core.php#/',
'wp-content/plugins/akismet/widget.php#/',
'xx.pl/',
'ls.php/',
'Cpanel.php/',
'k.php/',
'zone-h.php/',
'tmp/user.php/',
'tmp/Sym.phpcp.php/',
'tmp/madspotshell.php/',
'tmp/root.php/',
'tmp/whmcs.php/',
'tmp/index.php/',
'tmp/2.php/',
'tmp/dz.php/',
'tmp/cpn.php/',
'tmp/changeall.php/',
'tmp/Cgishell.pl/',
'tmp/sql.php0day.php/',
'tmp/admin.php/',
'cliente/downloads/h4xor.php/',
'whmcs/downloads/dz.phpL3b.php/',
'd.phptmp/d.php/',
'tmp/L3b.php/',
'wp-content/plugins/akismet/admin.php/',
'templates/rhuk_milkyway/index.php/',
'templates/beez/index.php/',
'sado.php/',
'admin1.php/',
'upload.php/',
'up.php/',
'admin2.aspuploads.php/',
'sa.php/',
'sysadmins/admin1/sniper.php/',
'administration/Sym.php/',
'images/Sym.php/',
'r57.php/',
'/wp-content/plugins/disqus-comment-system/disqus.phpgzaa_spyslsql-new.php/',
'shell.php/',
'sa.php/',
'admin.php/',
'sa2.php/',
'2.php/',
'gaza.php/',
'up.php/',
'upload.php/',
'uploads.php/',
'templates/beez/index.php/',
'shell.php/',
'amad.php/',
't00.php/',
'dz.php/',
'Black.php/',
'wp.php/',
'sysadmin.php/',
'images/c99.php/',
'xd.php/',
'c100.php/',
'spy.asp/',
'xxd.php/',
'tmp/xd.php/',
'sym/root/home/billing/killer.php/',
'tmp/upload.php/',
'tmp/admin.php/',
'Server.php/',
'tmp/uploads.php/',
'tmp/up.php/',
'Server/wp-admin/c99.php/',
'tmp/priv8.php/',
'priv8.php/',
'cgi.pl/',
'AnonG.php/',
'ACG.php/',
'Manisso.asp/',
'Manisso.php/',
'AnonG2.php/',
'tmp/cgi.pl/',
'downloads/dom.php/',
'templates/ja-helio-farsi/index.php/',
'webadmin.html/',
'admins.php/',
'bluff.php/',
'king.jeen/',
'admins/',
'admins.asp/',
'admins.php/',
'wp.zip/')
for link2 in link :

    link3 = url+"/"+link2

    try :

        openurl = urllib.request.urlopen(link3)

        print("\n\033[1;34m" + "Buldu : "+link3)





    except urllib.error.URLError as msg :

        print ("\n\033[33;39mBulunamadı Bekle : "+link3)

else:
     print("BİTTİ")
     exit()